--system tobiasz
--MY_TESTING MY_TESTING


--USERS + SEQENCE + TRIGGER
CREATE TABLE USERS(
    USR_ID NUMBER(10) PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL,
    SURNAME VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(50) NOT NULL
);

CREATE SEQUENCE USERS_USR_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
    
CREATE OR REPLACE TRIGGER USERS_USR_ID_TRG
    BEFORE INSERT ON USERS
    FOR EACH ROW
    BEGIN
        IF: NEW.USR_ID IS NULL THEN
        SELECT USERS_USR_ID_SEQ.NEXTVAL INTO :NEW.USR_ID FROM DUAL;
        END IF;
    END;
/


--PROD + SEQUENCE + TRIGGER + FK
CREATE TABLE PROD(
    PROD_ID NUMBER(10) PRIMARY KEY,
    STATUS CHAR(1) DEFAULT 'I' NOT NULL CHECK(STATUS IN ('A', 'I')),
    PROD_NAME VARCHAR(80) NOT NULL,
    PROD_FORM VARCHAR(20),
    PROD_STRENGTH VARCHAR2(20),
    PROD_PACKAGE VARCHAR2(20),
    MAH_ID NUMBER(10) NOT NULL,
    BLZ7 NUMBER(10),
    GTIN NUMBER(13),
    PROD_STOCK NUMBER(15,3) DEFAULT 0 NOT NULL CHECK(PROD_STOCK BETWEEN 0 AND 999999999),
    PROD_PRICE NUMBER(15,3) DEFAULT 0 NOT NULL CHECK(PROD_PRICE BETWEEN 0 AND 999999999)

    --CONSTRAINT PROD_MAH_MAH_ID_FK FOREIGN KEY (MAH_ID) REFERENCES MAH(MAH_ID)
);

CREATE SEQUENCE PROD_PROD_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE OR REPLACE TRIGGER PROD_PROD_ID_TRG
    BEFORE INSERT ON PROD
    FOR EACH ROW
    BEGIN
        IF: NEW.PROD_ID IS NULL THEN
        SELECT PROD_PROD_ID_SEQ.NEXTVAL INTO :NEW.PROD_ID FROM DUAL;
        END IF;
    END;
/



